extends: existence
ignorecase: true
level: warning
message: "Consider using an inclusive term instead of '%s'"
tokens:
  - master(?:s)
  - slave(?:s)
  - black hat(?:s)
  - blacklist(?:s)
  - dummy
  - man hour(?:s)
  - manmade
  - manpower
  - middleman
  - native
  - sanity
  - whitelist
