extends: substitution
message: "Use '%s' instead of '%s'."
level: warning
ignorecase: true
action:
  name: replace
swap:
  if you want to: to
  in order to: to
  in order for: for
  (?:as of late|of late): lately
  as per: per
  as a means of: to
  as long as: if
  as to whether: whether
  at a slow rate: slowly
  at a quick rate: quickly
  a number of: several, certain
  in accordance with: by, per, under
  do damage to: damage
  during the course of: during
  in the course of: during, in, over, or while
  for the duration of: during, through, for, or throughout
  for the purpose of: for, to
  in terms of: regarding
  make an effort: try
  in an effort to: to
  majority of: most
  previous to: before
  prior to: before
  take into consideration: consider
  with the exception of: except (for), apart (from)
  in the event that: if
  (?:have an effect on|have an impact on): affect, influence
  the way in which: how
  in a similar manner: similarly
  give the opportunity to: let, allow
  provide the ability to: let, allow
  are representative of: represent
  by means of: by, via
  by the use of: using, with
  by virtue of: because
  by way of: by, via
  in excess of: more than, over
  in the absence of: without
  (?:at the present time|as of this writing|at the time of publication|at the current time|at this point in time): now, currently
  due to the fact that: because, since
  despite the fact that: though, even though
  be aware of the fact that: know, understand
  in light of the fact that: because, considering
  in the direction of: toward
  make a choice: choose, decide
  indicative of: reveal, show, suggest
  on account of: because
  still remain: remain
  retain the same: retain
  minor tweaks: tweaks
  end result: result
  both of them: both
  trailing behind: trailing
  factor that plays a role: factor
  tailored to fit: tailored
  specific details: details
  check and see: check
  good-quality: quality
  notification alert: notification, or alert
  in close proximity to: close to, near
  debut of a new product: product debut
  a little bit: a bit (or a little)
  click on: click
  tap on: tap
  raise up: raise
  help out: help
  add together: add
  send out: send
