extends: substitution
message: "Consider using '%s' instead of '%s'."
level: warning
ignorecase: true
action:
  name: replace
swap:
  32-bit AMD/Intel: AMD64 / Intel 64|i586|i386|x86|IA-32
  AMD/Intel64|64-bit AMD/Intel|x64: x86-64|AMD64/Intel 64|x86_64
  ARM|ARM64: Arm®|Advanced RISC Machine|aarch64|armv8|arm64
  B\.T\.R\.F\.S|Better FS|BTRFS|btrfs: Btrfs
  Business-Critical Linux: BCL|Business Critical Linux
  ChangeLog|change-log|change log: changelog
  Chroot-script: chroot script
  Common UNIX Printing System|common Unix printing system|C\.U\.P\.S|cups|Cups: Common Unix Printing System|CUPS
  Containers-as-a-Service: Containers as a Service|CaaS
  Golden Master: Gold Master|GM
  Gpu: GPU|graphics processing unit
  IPV4|IPv4|IP v4: IPv4|Internet protocol version four
  Itanium|ipf: IA-64|Intel Itanium architecture|ia64
  KDUMP: Kdump
  NFS file system|N.F.S.|Nfs: NFS|Network File System
  NIS information service|N.I.S.|Nis: NIS|Network information system
  POWER8: ppc64|IBM Power|ppc64le|POWER
  PXE Boot: PXE boot|Preboot eXecution Environment
  Platform as a Service: PaaS|Platform-as-a-Service
  Problem Temporary Fix: PTF|Program Temporary Fix
  RISC V|risc-v|Risc v|Risc V|Risc-V: riscv64|RISC-V
  Rpm|R.P.M.: Redhat Package Manager|RPM|RPM Package Manager
  SSH Shell|SSH shell: Secure Shell Protocol|SSH
  System 500|system d|systemD|Systemd|System D: systemd
  XWS: X Window System
  abort|terminate|kill: close|cancel|stop|end|force quit|exit
  activation key|activation code: registration code
  addon|addOn|AddOn|add on: add-on|software add-on
  admin: administrator
  autologin|auto-login: auto login
  back door: backdoor|trap door|wormhole
  back end|backend: back-end
  baremetal|bare-metal: bare metal
  black hat hacker: unethical hacker|unethical attacker
  blacklist: blocklist|denylist
  bootdisk|boot-disk|boot disc: boot disk
  bootloader|boot-loader: boot loader
  carrier-grade: carrier grade|carrier class
  chip-set|chip set: chipset
  cold plug|cold-plug|coldadd|coldswap: coldplug
  cold-plugging|cold plugging|coldswapping|coldadding: coldplugging
  config(?!ure|uration|uring): configuration
  crashdump: crash dump
  dialog(?! box): dialog box
  drop(?!-down|-in): remove
  dummy value: sample value|placeholder value
  filename|file-name: file name
  filesystem hierarchy standard|file system hierarchy standard|File system Hierarchy Standard: FHS|Filesystem Hierarchy Standard
  filesystem|file-system: file system
  frame-buffer|frame buffer: framebuffer
  front end|frontend: front-end
  geo-cluster|geocluster: geo cluster|geographic cluster|geographically dispersed cluster
  grandfathered: legacy status
  hardlink|hard-link: hard link
  hostname: host name
  hot-plug|hotadd: hotswap
  hotadding|hot-plugging: hotplugging
  hotadding|hot-plugging: hotswapping
  hotadd|hot-plug|hot plug: hotplug
  initialization script|initscript|init-script: init script
  kernelspace|kernel-space: kernel space
  life-cycle|life cycle: lifecycle
  list field: list|list box
  man hours: engineer hours|management hours
  manual page: man page
  master branch: main branch
  master-slave|master/slave: parent/child|leader/follower|origin/clone|primary/secondary|leader/peer|parent/port|client/server
  mountpoint|mount-point: mount point
  multi-user|multi user: multiuser
  name space|name-space: namespace
  nameserver|name-server: name server
  native: built-in
  non-open source software: closed-source software
  on premise|on prem|on-prem|on-premise: on-premises
  pull-down menu|drop-down list box|drop-down menu|drop-down(?! list| box)|dropdown: drop-down list
  run-level|run level: runlevel
  run-time: runtime|run time
  sanity check|sanity test: quick check|confidence check|coherence check
  scsi|S.C.S.I.|Scsi: SCSI|Small Computer System Interface
  sd|SD|solidstate drive|solid state drive|solid-state disk|solid-state disk drive|solid state disc: solid-state drive|SSD
  slaves: workers
  supported on a best effort basis|best effort support|best-effort support: commercially reasonable support
  symlink: symbolic link|soft link
  synch: synchronization|sync
  tar-ball|tarball|tar ball: TAR archive|.tar|Tarball
  task-bar|task bar: desktop panel|panel|bottom edge panel|bottom panel|taskbar
  v12n: virtualization
  virtualisation platform: virtualization platform
  webmaster: web product owner
  webui: Web UI
  white hat hacker: ethical hacker
  white-space|white space: whitespace
  whitebox: clear box|open box
  whitelist: safe list|approved list|allowlist|ignorelist
  zSeries|z Systems: IBM Z|s390x|System z & LinuxONE|System z
