extends: substitution
message: Consider using '%s' instead of '%s'
ignorecase: false
nonword: true
level: error
action:
  name: replace
swap:
  Amd: AMD
  Bci: BCI
  command-line(?=,|:|;): command line
  Digikam|DigiKam|digikam|Digicam|digiCam|digicam: digiKam
  Fpga: FPGA
  E-book(?:s)|E-book(?:s)|Ebook(?:s)|eBook(?:s)|electronic book(?:s)|ebook(?:s): e-book
  E-mail(?:s)|E-mail(?:s)|Email(?:s)|eMail(?:s)|electronic mail(?:s)|email(?:s): e-mail
  E-PUB|e-PUB|e-Pub|EPub|Epub|ePUB|ePub: EPUB
  EXT3|EXT 3|Ext 3|Ext-3|ext 3|ext-3|ext3: Ext3
  EXT4|EXT 4|Ext 4|Ext-4|ext 4|ext-4|ext4: Ext4
  Gimp|gimp: GIMP
  Gnome|gnome: GNOME
  GIT: Git
  IPSEC|Ipsec: IPsec
  IP v6|IPV6|Ipv6: IPv6
  LiveCD|live-CD: live CD
  LiveDVD|live-DVD: Live DVD
  Linux mint: Linux Mint
  MacOS|Mac OS|mac OS: macOS
  Man page|Man-page|man page|man-page|manpage: man page
  Php: PHP
  POSTSCRIPT|Postscript|postscript: PostScript
  RAM memory|Ram|(?<=\s)ram: RAM
  Read-me(?:s)|Readme(?:s)|read-me(?:s)|readme(?:s): README
  SOC: SoC
  SAMBA|samba: Samba
  Sql: SQL
  SQlite|Sqlite: SQLite
  SuSE|SuSe|Suse: SUSE
  SysVinit|SysV init|system 5 init: System V init
  Wi fi|Wi-fi|Wifi|WLAN|wlan: Wi-Fi
  Url(?:s): URL
