extends: substitution
message: Use '%s' instead of '%s'
ignorecase: true
level: error
swap:
  32 Bit|32 bit|32-Bit|32Bit|32bit: 32-bit
  64 Bit|64 bit|64-Bit|64Bit|64bit: 64-bit
  check-box(?:s)|checkbox(?:s): check box
  check list(?:s)|check-list(?:s): checklist
  check-mark(?:s)|checkmark(?:s)|tick(?:s)|tick mark(?:s): check mark
  chip set(?:s)|chip-set(?:s): chipset
  code stream(?:s): codestream
  loop back device(?:s)|loop-back device(?:s): loopback device
  meta data|meta-data|metadatas: metadata
  patch-level(?:s)|patchlevel(?:s): patch level
  path-name(?:s)|pathname(?:s): path name
  pop up(?:s)|popup(?:s): pop-up
  printer queue(?:s)|printing queue(?:s): print queue
  printer spooler(?:s)|printing spooler(?:s): print spooler
  scroll-bar(?:s)|scroll bar(?:s): scrollbar
  stand alone|standalone: stand-alone
  status bar(?:s)|status-bar(?:s): statusbar
  sub director(?:y|ies)|sub-director(?:|ies): subdirectory
  sub menu(?:s)|sub-menu(?:s): submenu
  sub system(?:s)|sub-system(?:s): subsystem
  time-stamp(?:s)|timestamp(?:s): time stamp
  title bar(?:s)|title-bar(?:s): titlebar
  tool bar(?:s)|tool-bar(?:s): toolbar
  tool chain(?:s)|tool-chain(?:s): toolchain
  tool tip(?:s)|tool-tip(?:s): tooltip
  use-case(?:s)|usecase(?:s): use case
  user-name(?:s)|username(?:s): user name
