extends: substitution
message: "Use '%s' instead of '%s'."
level: warning
ignorecase: true
action:
  name: replace
swap:
  '(?:API Console|dev|developer) key': API key
  '(?:dev|developer|APIs) console': API console
  '(?:OAuth ?2|Oauth)': OAuth 2.0
  'un(?:check|select)': clear
  API explorer: APIs Explorer
  approx\.: approximately
  appendices: appendixes
  authN: authentication
  authZ: authorization
  autoupdate: automatically update
  content type: media type
  data are: data is
  firewalls: firewall rules
  grayed-out: unavailable
  HTTPs: HTTPS
  in order to: to
  ingest: import|loa
  network IP address: internal IP address
  (?:lower case|lower-case): lowercase
  pre-configured: preconfigured
  re-configure: reconfigure
  recreate: re-create
  regex: regular expression
  sign into: sign in to
  sign-?on: single sign-on
  some: certain
  style sheet: stylesheet
  (?:systemwide|system wide): system-wide
  tablename: table name
  (?:upper case|upper-case): uppercase
  (?:[^":])url: URL
  vs\.: versus
