extends: existence
message: "'%s' is too wordy"
ignorecase: true
level: warning
tokens:
  - a number of
  - adversely impact
  - aforementioned
  - all of
  - already existing
  - as of yet
  - as to
  - as yet
  - at the present time
  - at this time
  - because of the fact that
  - comply with
  - due to the fact that
  - first and foremost
  - for the most part
  - for the purpose of
  - if and when
  - in a timely manner
  - in accordance with
  - in addition
  - in an effort to
  - in many cases
  - in order to
  - in regard to
  - in some instances
  - in terms of
  - in the case of
  - in the event that
  - in the process of
  - is applicable to
  - is authorized to
  - is responsible for
  - it is essential
  - not many
  - not often
  - not unless
  - not unlike
  - numerous
  - on the other hand
  - one particular
  - point in time
  - provided that
  - readily available
  - take advantage of
  - some of the
  - with respect to
  - with the exception of
  
